### ISSUE TITLE
[Proposal] 번역 자료집 및 참고 자료 추가

### ISSUE THREAD

**Issue by seia-soto** [fastify/fastify-korean#5]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

독자에게 혼란을 야기할 수 있는 지점을 최소화하기 위해서 단어장 등 번역 자료집을 추가합니다. 이 경우에는 번역을 시작하기 전 단어를 어떻게 사용할 것인지 그리고 영어에만 문법이 존재하는 경우는 어떻게 처리할지 등의 사항을 넣는 것이 좋아보입니다.

### Motivation

제가 이전에 번역할 때에는 번역을 진행하면서 용어의 용법이 진행에 따라 변화한 점이 있습니다. 이 점에서 독자에게 혼란을 야기할 수 있으니 React와 같이 단어장 등을 추가하는 것을 제안합니다.

### Example

- https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary

**Comment by seia-soto** [comment]
관련하여 React 번역 프로젝트에서는 최대한 한국어 문법에 맞춘 바가 있으나 저는 영어 문법 기호들은 되려 축약을 한 형태로 더 빠르고 정리된 형태로 글을 작성할 수 있다고 생각이 됩니다. 이 경우에 선택적 허용을 하는 것도 좋은 방법이지 않을까 고견을 듣고 싶습니다.

**Comment by anniemon** [comment]
좋은 제안 감사합니다! 
말씀하신 대로 기술 용어는 최대한 원문을 살리고, 한글로 번역하지 않는 쪽으로 작업하는 것이 작업 속도도 빨라지고 읽기에도 편할 듯합니다.
가이드라인을 만들어보도록 하겠습니다 😊

**Comment by seia-soto** [comment]
9번 풀 리퀘스트 번역을 리뷰해보면서 몇 가지 관점이 생겨 공유드립니다. 그리고 React 번역팀의 정책을 비교군으로 달아놨습니다.

1. 불필요한 문장 부호들은 제거하는 것이 간결했습니다. [쉼표](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation#%EC%89%BC%ED%91%9C%EB%A5%BC-%EB%AA%A8%EB%91%90-%EC%98%AE%EA%B8%B8-%ED%95%84%EC%9A%94%EB%8A%94-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4)
2. "우리", "저희"나 "당신"과 같은 경우에는 튜토리얼/가이드 등이 아닌 일상적이거나 Fastify 팀을 대표하는 자리에서는 유효하게 작동합니다. [우리 및 당신](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation#%EB%8B%B9%EC%8B%A0%EA%B3%BC-%EC%97%AC%EB%9F%AC%EB%B6%84%EC%9D%80-%EC%97%86%EC%96%B4%EB%8F%84-%EB%90%A9%EB%8B%88%EB%8B%A4)
3. 단수형을 지향하는 편이 확실히 깔끔합니다. [단수 및 복수형](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation#%EC%96%B4%EC%83%89%ED%95%98%EC%A7%80-%EC%95%8A%EB%8B%A4%EB%A9%B4-%EB%8B%A8%EC%88%98%ED%98%95%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%A9%EC%8B%9C%EB%8B%A4)

https://github.com/fastify/fastify-korean/pull/9#pullrequestreview-1047757341

> 수정 1: 지양 -> 지향

**Comment by anniemon** [comment]
레퍼런스 감사합니다! 
React 번역팀의 위키에 참고할 내용이 많네요. 검토하여 가이드라인에 반영해보겠습니다.
3번에 의도하신 바는 단수형을 '지향'하는 것이 좋다는 의견이 맞을까요?

우선 가이드라인 초안으로 작성해본 내용을 공유합니다. 읽어보시고 시간될 때 리뷰 남겨주시면 좋겠습니다.

### 번역 가이드라인
- 반드시 아래 사항을 모두 지켜야 merge되는 것은 아닙니다. 
- 문맥에 따라 역자의 판단을 우선할 수 있습니다. 하지만 가이드라인을 인지하고, 고려하여 번역해주시기 바랍니다.

1. 가능한 피동형 보다는 능동형을 사용합니다.
ex. 제거될(x), 제거할(o)
사용될(x), 사용할(o)

2. 예제 코드에서 그대로 사용하는 기술 용어이거나, 널리 사용하는 개발 용어인 경우 번역하지 않아도 무방합니다. 그러나 하나의 아티클에서는 통일성을 유지해주세요.
ex. request -> 리퀘스트(o), 요청(o)
body -> 바디(o), 본문(o)
error -> 에러(o), 오류(o)
parsing -> 파싱(o), 구문 분석(o)

5. '하십시오(합쇼)체'를 기본으로 하되 ‘해요체'를 섞어 써도 무방합니다. 다만 해요체를 쓸 때는 경어를 사용합니다.
ex. ‘-합니다.’ (o), ‘-하세요’ (o), ‘해요.’ (x)

6. 가능한 복수형은 생략합니다.
ex. 예제들을(x), 예제를(o)
객체들에(x), 객체에(o)

번역에 관한 제안 사항은 이슈에 등록해주세요.

**Comment by seia-soto** [comment]
네! 3번은 지양이 아닌 지향이 맞습니다.

### 용어와 단어집

기본적인 사항은 이미 높은 수준의 품질을 제공하는 React 기술 문서를 거의 따라가는 것으로 보입니다. 특히 2번과 같은 경우에는 단어집을 따로 사용하는 제공하는 것이 훨씬 좋아 보이네요. 저는 프로그래밍을 대부분의 사람들이 정규화된 교육 과정 하에 배우는 것이 아니기에 우리말 번역이 있다고 하더라도 "구문 분석"과 같은 경우에는 "파싱"이 실상 더 많은 사람들이 편하게 읽을 것이라 생각합니다. 물론 "구문 분석"이라는 용어를 대부분 에디터와 같은 유틸리티의 한글 버전에서 사용하고 있긴 하여 두 경우 모두 큰 무리는 없을 것으로 보입니다.

일단은 번역을 지금은 제가 직접적으로 하는 편이 아니다보니 1차적인 번역 중에라도 느끼시는 바에 따라 결정을 지으실 수 있으리라 판단됩니다. 저의 경우에는 당시 번역할 때 "구문 분석"이라고 표기하는 편이 "파싱"과 같은 동사형보다 깔끔하게 보였습니다. 물론 실 번역본에는 생각이 계속 바뀌어서 왔다갔다 하지만요.

### -시-는 제한적으로 사용합니다

또 다른 리액트 쪽 번역 규칙인 [React: 시는 제한적으로 사용합니다](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation#%EC%8B%9C%EB%8A%94-%EC%A0%9C%ED%95%9C%EC%A0%81%EC%9C%BC%EB%A1%9C-%EC%82%AC%EC%9A%A9%ED%95%A9%EB%8B%88%EB%8B%A4)의 규칙도 추가하면 좋을 것으로 예상되는데 추가 코멘트로 "이 경우엔 직역이 아니라 의역이 될 수 있다"는 점이 있다면 번역 중 소실되는 부분에 관해서도 좋은 가이드라인이 될 것입니다.

예를 들어서 `good to see ~~`와 같은 꼴에서 `~~도 보시면 좋습니다`를 경우에 따라 단순함을 위해 `~~도 확인해보세요.`와 같이 단순 치환시킬 경우에는 `good` 등 형용사 문이 모두 소실되다 보니 처음 번역을 하는 사람에게 혼동이 있을 수 있을 겁니다.

### `A 및 B` vs `A와 B`

이 경우에도 많은 혼선이 있을 것으로 보이며 "경우에 따라 가능하면" 일관성을 제공하고 문서화하면 더 좋을 것 같습니다. 저와 같은 경우에는 읽으면서 글의 구조가 어느 것이 더 효과적으로 들어올지 생각을 해보았는데 맥락에 따라 달라지는 점이 있어 이 부분은 어떻게 생각하시는지 의견을 여쭙고 싶습니다.

1) A 및 B: B가 A의 부가 설명이 되는 것처럼 느껴집니다
2) A와 B: A와 B는 동등한 위치에서 해석됩니다

**Comment by seia-soto** [comment]
시간이 나면 다시 문서를 보면서 머릿속에 정보가 쌓이는 구조를 생각해 보아야겠습니다. 혼자 번역할 때보다도 훨씬 많은 인사이트를 받게 되는 기분이네요. 감사합니다.

**Comment by anniemon** [comment]
`A 및 B` vs `A와 B`
둘의 의미상의 차이는 거의 없는 것 같습니다. `및`을 사용하면 좀 더 딱딱해보이는 느낌은 드네요. 말씀하신 대로 맥락에 따라 다르게 읽힐 여지도 있는 듯하나, 역자의 취향에 따라 갈릴 수 있는 부분이라 가이드라인에 포함하기엔 애매한 것 같습니다.

높임말 `-시`를 제한적으로 사용하는 것이 좋다는 의견에 동의합니다. 다만 번역 중 의미 소실에 관한 문제는 다른 이야기 같아요. `good to see`를 `~~도 보면 좋습니다`로 `-시` 없이 의미를 살려 번역할 수도 있으니까요.

개인적으로 높은 수준의 번역 품질과 일관성을 추구하기 보다는 빠르게 1차 번역을 완료하여 많은 사용자가 문서를 이용할 수 있게 하는 것이 우선이라고 생각합니다. 따라서 타이트한 가이드라인을 제공하려고 하지는 않습니다.

제안해주신 내용과 리액트 번역 모범사례를 참고하여 번역 가이드라인을 추가했습니다.

지금은 단어가 많이 쌓이지 않은 듯하여, 단어집은 차차 추가해보겠습니다.
저도 번역에 대해 새롭게 생각해보게 되네요. 좋은 의견 주셔서 감사합니다😊
